/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import { jsonColumn, bigIntColumn, booleanColumn, encryptedColumn, encryptedJsonColumn } from '#database/columns'
import type { ApiScope } from '#api/scopes'
import type { EntitlementValue, EntitlementValues } from '#catalog/entitlements'

export class ApiKeySchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'expiresAt', 'id', 'keyHash', 'lastUsedAt', 'name', 'organizationId', 'prefix', 'publicId', 'revokedAt', 'scopes', 'updatedAt'] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keyHash: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare organizationId: number
  @column()
  declare prefix: string
  @column()
  declare publicId: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @jsonColumn()
  declare scopes: ApiScope[]
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ApiRequestSchema extends BaseModel {
  static $columns = ['apiKeyId', 'createdAt', 'durationMs', 'id', 'ip', 'method', 'organizationId', 'path', 'requestId', 'status'] as const
  $columns = ApiRequestSchema.$columns
  @column()
  declare apiKeyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ip: string | null
  @column()
  declare method: string
  @column()
  declare organizationId: number
  @column()
  declare path: string
  @column()
  declare requestId: string | null
  @column()
  declare status: number
}

export class ApiUsageDaySchema extends BaseModel {
  static $columns = ['createdAt', 'day', 'errors', 'id', 'organizationId', 'requests', 'updatedAt'] as const
  $columns = ApiUsageDaySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare day: string
  @column()
  declare errors: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column()
  declare requests: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorId', 'actorType', 'createdAt', 'id', 'ip', 'metadata', 'organizationId', 'subjectId', 'subjectType', 'userAgent'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorId: number | null
  @column()
  declare actorType: 'user' | 'staff' | 'api_key' | 'system'
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ip: string | null
  @jsonColumn()
  declare metadata: Record<string, any> | null
  @column()
  declare organizationId: number | null
  @column()
  declare subjectId: string | null
  @column()
  declare subjectType: string | null
  @column()
  declare userAgent: string | null
}

export class AuthTokenSchema extends BaseModel {
  static $columns = ['consumedAt', 'createdAt', 'expiresAt', 'id', 'tokenHash', 'type', 'userId'] as const
  $columns = AuthTokenSchema.$columns
  @column.dateTime()
  declare consumedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column()
  declare type: 'verify_email' | 'reset_password'
  @column()
  declare userId: number
}

export class EntitlementSchema extends BaseModel {
  static $columns = ['createdAt', 'defaultValue', 'description', 'id', 'key', 'name', 'productId', 'publicId', 'type', 'updatedAt'] as const
  $columns = EntitlementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @jsonColumn()
  declare defaultValue: EntitlementValue | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare name: string
  @column()
  declare productId: number
  @column()
  declare publicId: string
  @column()
  declare type: 'boolean' | 'integer' | 'string'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FileSchema extends BaseModel {
  static $columns = ['attachableId', 'attachableType', 'checksum', 'createdAt', 'deletedAt', 'disk', 'id', 'key', 'mimeType', 'organizationId', 'originalName', 'publicId', 'sizeBytes', 'updatedAt', 'userId', 'visibility'] as const
  $columns = FileSchema.$columns
  @column()
  declare attachableId: number | null
  @column()
  declare attachableType: 'User' | 'Organization' | 'SupportMessage' | null
  @column()
  declare checksum: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare disk: 'private' | 'public'
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare mimeType: string
  @column()
  declare organizationId: number
  @column()
  declare originalName: string
  @column()
  declare publicId: string
  @bigIntColumn()
  declare sizeBytes: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare visibility: 'private' | 'public'
}

export class InvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'expiresAt', 'id', 'invitedByUserId', 'organizationId', 'publicId', 'revokedAt', 'role', 'tokenHash', 'updatedAt'] as const
  $columns = InvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedByUserId: number | null
  @column()
  declare organizationId: number
  @column()
  declare publicId: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare role: 'owner' | 'member'
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JobSchema extends BaseModel {
  static $columns = ['attempts', 'availableAt', 'createdAt', 'failedAt', 'id', 'lastError', 'maxAttempts', 'name', 'payload', 'queue', 'reservedAt', 'reservedBy', 'updatedAt'] as const
  $columns = JobSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime()
  declare availableAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare failedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column()
  declare maxAttempts: number
  @column()
  declare name: string
  @jsonColumn()
  declare payload: Record<string, any> | null
  @column()
  declare queue: string
  @column.dateTime()
  declare reservedAt: DateTime | null
  @column()
  declare reservedBy: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['actionLabel', 'actionUrl', 'audience', 'audienceType', 'body', 'createdAt', 'createdByStaffId', 'deletedAt', 'expiresAt', 'id', 'level', 'publicId', 'publishedAt', 'title', 'updatedAt'] as const
  $columns = NotificationSchema.$columns
  @column()
  declare actionLabel: string | null
  @column()
  declare actionUrl: string | null
  @jsonColumn()
  declare audience: { planKeys?: string[]; userIds?: number[] } | null
  @column()
  declare audienceType: 'all' | 'plan' | 'owners' | 'users'
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByStaffId: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: 'info' | 'success' | 'warning' | 'error'
  @column()
  declare publicId: string
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'limitOverrides', 'logoKey', 'name', 'ownerId', 'planKey', 'publicId', 'slug', 'status', 'storageUsedBytes', 'timezone', 'trialEndsAt', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @jsonColumn()
  declare limitOverrides: Record<string, number | null> | null
  @column()
  declare logoKey: string | null
  @column()
  declare name: string
  @column()
  declare ownerId: number | null
  @column()
  declare planKey: string
  @column()
  declare publicId: string
  @column()
  declare slug: string
  @column()
  declare status: 'active' | 'past_due' | 'canceled' | 'suspended'
  @bigIntColumn()
  declare storageUsedBytes: number
  @column()
  declare timezone: string
  @column.dateTime()
  declare trialEndsAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amountCents', 'createdAt', 'currency', 'description', 'id', 'occurredAt', 'organizationId', 'provider', 'providerOrderId', 'publicId', 'receiptUrl', 'refundedAmountCents', 'status', 'subscriptionId', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amountCents: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare organizationId: number
  @column()
  declare provider: 'creem'
  @column()
  declare providerOrderId: string
  @column()
  declare publicId: string
  @column()
  declare receiptUrl: string | null
  @column()
  declare refundedAmountCents: number
  @column()
  declare status: 'succeeded' | 'refunded' | 'partially_refunded' | 'disputed'
  @column()
  declare subscriptionId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PlanSchema extends BaseModel {
  static $columns = ['billing', 'createdAt', 'currency', 'entitlements', 'id', 'isPublic', 'licenseTerm', 'maxActivations', 'name', 'priceCents', 'productId', 'providerProductId', 'publicId', 'slug', 'sortOrder', 'status', 'termDays', 'updatedAt', 'updatesDays'] as const
  $columns = PlanSchema.$columns
  @column()
  declare billing: 'one_time' | 'monthly' | 'yearly'
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @jsonColumn()
  declare entitlements: EntitlementValues | null
  @column({ isPrimary: true })
  declare id: number
  @booleanColumn()
  declare isPublic: boolean
  @column()
  declare licenseTerm: 'perpetual' | 'subscription' | 'fixed_days'
  @column()
  declare maxActivations: number | null
  @column()
  declare name: string
  @column()
  declare priceCents: number
  @column()
  declare productId: number
  @column()
  declare providerProductId: string | null
  @column()
  declare publicId: string
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column()
  declare status: 'active' | 'archived'
  @column()
  declare termDays: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatesDays: number | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['countDevSites', 'createdAt', 'description', 'docsUrl', 'homepageUrl', 'id', 'keyPrefix', 'kind', 'name', 'offlineGraceDays', 'publicId', 'slug', 'status', 'updatedAt', 'validationIntervalHours'] as const
  $columns = ProductSchema.$columns
  @booleanColumn()
  declare countDevSites: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare docsUrl: string | null
  @column()
  declare homepageUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keyPrefix: string
  @column()
  declare kind: 'wordpress_plugin' | 'app' | 'library' | 'other'
  @column()
  declare name: string
  @column()
  declare offlineGraceDays: number
  @column()
  declare publicId: string
  @column()
  declare slug: string
  @column()
  declare status: 'draft' | 'active' | 'retired'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare validationIntervalHours: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class SocialAccountSchema extends BaseModel {
  static $columns = ['accessToken', 'createdAt', 'id', 'provider', 'providerEmail', 'providerUserId', 'updatedAt', 'userId'] as const
  $columns = SocialAccountSchema.$columns
  @encryptedColumn()
  declare accessToken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare provider: 'google' | 'github'
  @column()
  declare providerEmail: string | null
  @column()
  declare providerUserId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class StaffUserSchema extends BaseModel {
  static $columns = ['createdAt', 'disabledAt', 'email', 'fullName', 'id', 'lastLoginAt', 'password', 'publicId', 'role', 'twoFactorConfirmedAt', 'twoFactorRecoveryCodes', 'twoFactorSecret', 'updatedAt'] as const
  $columns = StaffUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare disabledAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare publicId: string
  @column()
  declare role: 'admin' | 'support'
  @column.dateTime()
  declare twoFactorConfirmedAt: DateTime | null
  @encryptedJsonColumn()
  declare twoFactorRecoveryCodes: string[] | null
  @encryptedColumn()
  declare twoFactorSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['cancelAtPeriodEnd', 'canceledAt', 'createdAt', 'currentPeriodEnd', 'currentPeriodStart', 'id', 'organizationId', 'planKey', 'provider', 'providerCustomerId', 'providerSubscriptionId', 'status', 'trialEndsAt', 'updatedAt'] as const
  $columns = SubscriptionSchema.$columns
  @booleanColumn()
  declare cancelAtPeriodEnd: boolean
  @column.dateTime()
  declare canceledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare currentPeriodEnd: DateTime | null
  @column.dateTime()
  declare currentPeriodStart: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column()
  declare planKey: string
  @column()
  declare provider: 'creem'
  @column()
  declare providerCustomerId: string | null
  @column()
  declare providerSubscriptionId: string
  @column()
  declare status: 'trialing' | 'active' | 'past_due' | 'paused' | 'canceled' | 'expired'
  @column.dateTime()
  declare trialEndsAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SupportMessageSchema extends BaseModel {
  static $columns = ['authorStaffId', 'authorType', 'authorUserId', 'body', 'createdAt', 'id', 'publicId', 'supportTicketId', 'updatedAt'] as const
  $columns = SupportMessageSchema.$columns
  @column()
  declare authorStaffId: number | null
  @column()
  declare authorType: 'user' | 'staff'
  @column()
  declare authorUserId: number | null
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare publicId: string
  @column()
  declare supportTicketId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SupportTicketSchema extends BaseModel {
  static $columns = ['assignedStaffId', 'createdAt', 'createdByUserId', 'deletedAt', 'firstRespondedAt', 'id', 'lastMessageAt', 'organizationId', 'publicId', 'resolvedAt', 'status', 'subject', 'updatedAt'] as const
  $columns = SupportTicketSchema.$columns
  @column()
  declare assignedStaffId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime()
  declare firstRespondedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastMessageAt: DateTime
  @column()
  declare organizationId: number
  @column()
  declare publicId: string
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare status: 'open' | 'answered' | 'resolved'
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TodoListSchema extends BaseModel {
  static $columns = ['archivedAt', 'color', 'createdAt', 'createdByUserId', 'deletedAt', 'description', 'id', 'name', 'organizationId', 'position', 'publicId', 'todosCount', 'updatedAt'] as const
  $columns = TodoListSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare color: 'blue' | 'green' | 'orange' | 'purple' | 'red' | 'gray'
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare organizationId: number
  @column()
  declare position: number
  @column()
  declare publicId: string
  @column()
  declare todosCount: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TodoSchema extends BaseModel {
  static $columns = ['assignedToUserId', 'completedAt', 'completedByUserId', 'createdAt', 'createdByUserId', 'deletedAt', 'dueAt', 'id', 'notes', 'organizationId', 'position', 'priority', 'publicId', 'title', 'todoListId', 'updatedAt'] as const
  $columns = TodoSchema.$columns
  @column()
  declare assignedToUserId: number | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare completedByUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime()
  declare dueAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare organizationId: number
  @column()
  declare position: number
  @column()
  declare priority: 'low' | 'normal' | 'high'
  @column()
  declare publicId: string
  @column()
  declare title: string
  @column()
  declare todoListId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarKey', 'createdAt', 'deletedAt', 'email', 'emailVerifiedAt', 'fullName', 'id', 'lastLoginAt', 'notificationsSeenAt', 'organizationId', 'password', 'publicId', 'role', 'twoFactorConfirmedAt', 'twoFactorRecoveryCodes', 'twoFactorSecret', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarKey: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime()
  declare notificationsSeenAt: DateTime | null
  @column()
  declare organizationId: number
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare publicId: string
  @column()
  declare role: 'owner' | 'member'
  @column.dateTime()
  declare twoFactorConfirmedAt: DateTime | null
  @encryptedJsonColumn()
  declare twoFactorRecoveryCodes: string[] | null
  @encryptedColumn()
  declare twoFactorSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WebhookEventSchema extends BaseModel {
  static $columns = ['attempts', 'eventType', 'id', 'lastError', 'payload', 'processedAt', 'provider', 'providerEventId', 'receivedAt', 'signatureVerified'] as const
  $columns = WebhookEventSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare eventType: 'subscription.activated' | 'subscription.updated' | 'subscription.trialing' | 'subscription.past_due' | 'subscription.paused' | 'subscription.canceled' | 'payment.succeeded' | 'payment.refunded' | 'dispute.created'
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @jsonColumn()
  declare payload: Record<string, any> | null
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare provider: 'creem'
  @column()
  declare providerEventId: string
  @column.dateTime()
  declare receivedAt: DateTime
  @booleanColumn()
  declare signatureVerified: boolean
}
