import vine from '@vinejs/vine'

/**
 * The public license API's request bodies (licence plan §6). snake_case on
 * the wire, like the rest of the API.
 *
 * Deliberately loose about the key itself — any string up to 128 characters
 * — because a malformed key is a business answer (`invalid_license`), not a
 * 422. A client that sends *something* in the key field always gets a
 * decision back.
 */

const product = vine
  .string()
  .trim()
  .maxLength(64)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)

const licenseKey = vine.string().trim().minLength(1).maxLength(128)

/**
 * Generated by the client once per installation and kept. A UUID is the
 * expected shape; anything conservative enough to log and put in a URL is
 * accepted.
 */
const instanceId = vine
  .string()
  .trim()
  .regex(/^[A-Za-z0-9._:-]{1,64}$/)

/**
 * Echoed inside the signed payload, so a client can tell a fresh answer to
 * *this* request from a replay of an old signed one.
 */
const nonce = vine
  .string()
  .trim()
  .regex(/^[A-Za-z0-9._-]{8,64}$/)
  .optional()

export const validateLicenseValidator = vine.create({
  product,
  license_key: licenseKey,
  instance_id: instanceId.optional(),
  nonce,
})

export const activateLicenseValidator = vine.create({
  product,
  license_key: licenseKey,
  instance_id: instanceId,
  site_url: vine.string().trim().maxLength(1024).nullable().optional(),
  label: vine.string().trim().maxLength(120).nullable().optional(),
  client_version: vine.string().trim().maxLength(32).nullable().optional(),
  nonce,
})

export const deactivateLicenseValidator = vine.create({
  product,
  license_key: licenseKey,
  instance_id: instanceId,
  nonce,
})

/**
 * `GET /products/:slug/releases/latest` (licence plan §6, M7). A query
 * string, because WordPress asks for updates with a GET; every field is
 * optional, since a free build is offered to anybody.
 */
export const latestReleaseValidator = vine.create({
  channel: vine.enum(['stable', 'beta'] as const).optional(),
  license_key: licenseKey.optional(),
  instance_id: instanceId.optional(),
  nonce,
})
