/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    AuditLog: () => import('#app/controllers/admin/audit_log_controller'),
    Dashboard: () => import('#app/controllers/admin/dashboard_controller'),
    Entitlement: () => import('#app/controllers/admin/entitlement_controller'),
    Impersonation: () => import('#app/controllers/admin/impersonation_controller'),
    Job: () => import('#app/controllers/admin/job_controller'),
    License: () => import('#app/controllers/admin/license_controller'),
    Notification: () => import('#app/controllers/admin/notification_controller'),
    Organization: () => import('#app/controllers/admin/organization_controller'),
    Plan: () => import('#app/controllers/admin/plan_controller'),
    Product: () => import('#app/controllers/admin/product_controller'),
    Session: () => import('#app/controllers/admin/session_controller'),
    Staff: () => import('#app/controllers/admin/staff_controller'),
    Subscription: () => import('#app/controllers/admin/subscription_controller'),
    Support: () => import('#app/controllers/admin/support_controller'),
    User: () => import('#app/controllers/admin/user_controller'),
    Webhook: () => import('#app/controllers/admin/webhook_controller'),
  },
  apiKeys: {
    ApiKey: () => import('#app/controllers/api_keys/api_key_controller'),
  },
  api: {
    v1: {
      License: () => import('#app/controllers/api/v1/license_controller'),
      Organization: () => import('#app/controllers/api/v1/organization_controller'),
      Product: () => import('#app/controllers/api/v1/product_controller'),
    },
  },
  auth: {
    EmailVerification: () => import('#app/controllers/auth/email_verification_controller'),
    InvitationAcceptance: () => import('#app/controllers/auth/invitation_acceptance_controller'),
    PasswordReset: () => import('#app/controllers/auth/password_reset_controller'),
    Registration: () => import('#app/controllers/auth/registration_controller'),
    Session: () => import('#app/controllers/auth/session_controller'),
    SocialAuth: () => import('#app/controllers/auth/social_auth_controller'),
    TwoFactorChallenge: () => import('#app/controllers/auth/two_factor_challenge_controller'),
  },
  billing: {
    Billing: () => import('#app/controllers/billing/billing_controller'),
    Webhook: () => import('#app/controllers/billing/webhook_controller'),
  },
  Dashboard: () => import('#app/controllers/dashboard_controller'),
  docs: {
    Docs: () => import('#app/controllers/docs/docs_controller'),
  },
  files: {
    File: () => import('#app/controllers/files/file_controller'),
  },
  Health: () => import('#app/controllers/health_controller'),
  notifications: {
    Notification: () => import('#app/controllers/notifications/notification_controller'),
  },
  organizations: {
    Invitation: () => import('#app/controllers/organizations/invitation_controller'),
    Member: () => import('#app/controllers/organizations/member_controller'),
    Ownership: () => import('#app/controllers/organizations/ownership_controller'),
  },
  settings: {
    Organization: () => import('#app/controllers/settings/organization_controller'),
    Profile: () => import('#app/controllers/settings/profile_controller'),
    Security: () => import('#app/controllers/settings/security_controller'),
  },
  support: {
    Support: () => import('#app/controllers/support/support_controller'),
  },
  lists: {
    api: {
      List: () => import('#app/modules/lists/controllers/api/list_controller'),
      Todo: () => import('#app/modules/lists/controllers/api/todo_controller'),
    },
    List: () => import('#app/modules/lists/controllers/list_controller'),
    Todo: () => import('#app/modules/lists/controllers/todo_controller'),
  },
}
