/**
 * The demo domain's half of the OpenAPI document (plan §11).
 *
 * The spec is written by hand from the transformers and validators rather
 * than generated by reflection — a generated one silently changes shape the
 * moment somebody adds a column, which is the exact failure the transformers
 * exist to prevent.
 *
 * It lives with the feature it documents, and `start/api.ts` registers it, so
 * removing the domain removes its endpoints from `/openapi.json` and `/docs`
 * without editing either (docs/modules.md).
 *
 * The shared pieces — the cursor parameters, the envelope helpers, the common
 * error responses and the `402` — come from `#api/openapi`, so a feature's
 * endpoints are documented the same way core's are.
 */

import {
  commonResponses,
  cursorParams,
  errorSchema,
  item,
  json,
  page,
  planLimitResponse,
  type OpenApiContribution,
} from '#api/openapi'

const listSchema = {
  type: 'object',
  properties: {
    id: { type: 'string', example: 'lst_7fj2k9pqrstu' },
    name: { type: 'string' },
    description: { type: 'string', nullable: true },
    color: { type: 'string', enum: ['blue', 'green', 'orange', 'purple', 'red', 'gray'] },
    position: { type: 'integer' },
    todos_count: {
      type: 'integer',
      description:
        'Counts completed todos too. This is the number the todosPerList limit is checked against.',
    },
    archived: { type: 'boolean' },
    archived_at: { type: 'string', format: 'date-time', nullable: true },
    created_at: { type: 'string', format: 'date-time' },
    updated_at: { type: 'string', format: 'date-time', nullable: true },
  },
} as const

const todoSchema = {
  type: 'object',
  properties: {
    id: { type: 'string', example: 'tdo_7fj2k9pqrstu' },
    list_id: { type: 'string', example: 'lst_7fj2k9pqrstu' },
    title: { type: 'string' },
    notes: { type: 'string', nullable: true },
    priority: { type: 'string', enum: ['low', 'normal', 'high'] },
    position: { type: 'integer' },
    due_at: { type: 'string', format: 'date-time', nullable: true },
    completed: { type: 'boolean' },
    completed_at: { type: 'string', format: 'date-time', nullable: true },
    assigned_to: {
      type: 'string',
      nullable: true,
      description: "A member's id. An id from another organisation is a 422, never a silent null.",
    },
    created_at: { type: 'string', format: 'date-time' },
    updated_at: { type: 'string', format: 'date-time', nullable: true },
  },
} as const

export const listOpenApi: OpenApiContribution = {
  schemas: {
    List: listSchema,
    Todo: todoSchema,
  },

  paths: {
    '/lists': {
      get: {
        summary: 'List lists',
        parameters: [
          ...cursorParams,
          {
            name: 'archived',
            in: 'query',
            schema: { type: 'string', enum: ['true', 'false', 'all'] },
            description: 'Omit for live lists only. Archived lists still count against quota.',
          },
        ],
        responses: {
          200: { description: 'A page of lists.', ...json(page(listSchema)) },
          ...commonResponses,
        },
      },
      post: {
        summary: 'Create a list',
        requestBody: json({
          type: 'object',
          required: ['name'],
          properties: {
            name: { type: 'string', maxLength: 120 },
            description: { type: 'string', nullable: true, maxLength: 500 },
            color: listSchema.properties.color,
          },
        }),
        responses: {
          201: { description: 'Created.', ...json(item(listSchema)) },
          422: { description: 'Invalid body, or a duplicate name.', ...json(errorSchema) },
          ...planLimitResponse,
          ...commonResponses,
        },
      },
    },

    '/lists/{id}': {
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      get: {
        summary: 'Fetch a list',
        responses: {
          200: { description: 'The list.', ...json(item(listSchema)) },
          ...commonResponses,
        },
      },
      patch: {
        summary: 'Update a list',
        description: 'Archiving is a field here, so a rename and an archive are one call.',
        requestBody: json({
          type: 'object',
          properties: {
            name: { type: 'string', maxLength: 120 },
            description: { type: 'string', nullable: true, maxLength: 500 },
            color: listSchema.properties.color,
            archived: { type: 'boolean' },
          },
        }),
        responses: {
          200: { description: 'The updated list.', ...json(item(listSchema)) },
          422: { description: 'Invalid body, or a duplicate name.', ...json(errorSchema) },
          ...commonResponses,
        },
      },
      delete: {
        summary: 'Delete a list and its todos',
        description:
          'Soft delete, and it frees quota. Requires `lists:write` — a read-only key cannot do this by any route.',
        responses: { 204: { description: 'Deleted.' }, ...commonResponses },
      },
    },

    '/lists/{id}/todos': {
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      get: {
        summary: 'List todos in a list',
        parameters: [
          ...cursorParams,
          { name: 'completed', in: 'query', schema: { type: 'string', enum: ['true', 'false'] } },
          {
            name: 'assigned_to',
            in: 'query',
            schema: { type: 'string' },
            description: 'A member id. An unknown id matches nothing rather than erroring.',
          },
        ],
        responses: {
          200: { description: 'A page of todos.', ...json(page(todoSchema)) },
          ...commonResponses,
        },
      },
      post: {
        summary: 'Create a todo',
        description:
          'Completed todos still count against `todosPerList`, so a full list stays full until todos are deleted or moved.',
        requestBody: json({
          type: 'object',
          required: ['title'],
          properties: {
            title: { type: 'string', maxLength: 200 },
            notes: { type: 'string', nullable: true, maxLength: 2000 },
            priority: todoSchema.properties.priority,
            due_at: { type: 'string', format: 'date-time', nullable: true },
            assigned_to: { type: 'string', nullable: true },
          },
        }),
        responses: {
          201: { description: 'Created.', ...json(item(todoSchema)) },
          422: {
            description: 'Invalid body, or an `assigned_to` outside this organisation.',
            ...json(errorSchema),
          },
          ...planLimitResponse,
          ...commonResponses,
        },
      },
    },

    '/todos/{id}': {
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      get: {
        summary: 'Fetch a todo',
        responses: {
          200: { description: 'The todo.', ...json(item(todoSchema)) },
          ...commonResponses,
        },
      },
      patch: {
        summary: 'Update a todo',
        requestBody: json({
          type: 'object',
          properties: {
            title: { type: 'string', maxLength: 200 },
            notes: { type: 'string', nullable: true, maxLength: 2000 },
            priority: todoSchema.properties.priority,
            due_at: { type: 'string', format: 'date-time', nullable: true },
            assigned_to: { type: 'string', nullable: true },
            position: { type: 'integer', minimum: 0 },
          },
        }),
        responses: {
          200: { description: 'The updated todo.', ...json(item(todoSchema)) },
          422: { description: 'Invalid body.', ...json(errorSchema) },
          ...commonResponses,
        },
      },
      delete: {
        summary: 'Delete a todo',
        description: 'Soft delete. Frees a slot against `todosPerList`.',
        responses: { 204: { description: 'Deleted.' }, ...commonResponses },
      },
    },

    '/todos/{id}/complete': {
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      post: {
        summary: 'Mark a todo complete',
        description:
          'Records who completed it and when. Idempotent — completing a done todo succeeds.',
        responses: {
          200: { description: 'The todo.', ...json(item(todoSchema)) },
          ...commonResponses,
        },
      },
    },

    '/todos/{id}/uncomplete': {
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      post: {
        summary: 'Mark a todo not complete',
        responses: {
          200: { description: 'The todo.', ...json(item(todoSchema)) },
          ...commonResponses,
        },
      },
    },
  },
}
